# Generated by Django 5.1.4 on 2025-01-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_studentrank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrank',
            name='date_of_report_card_generation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentrank',
            unique_together={('student', 'date_of_report_card_generation')},
        ),
    ]
